name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers on pushes to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the environment for the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checks out your code

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Change according to your Java version

      - name: Build with Maven
        run: mvn clean install  # Command to build your project

      - name: Run tests
        run: mvn test  # Command to run your tests

      - name: Deploy
        run: |
          echo "Deploying application..."  # Add deployment commands here
